server:
  port: 7777
spring:
  application:
    name: vlog-zuul-proxy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    password: root
    url: jdbc:mysql://localhost:3306/vlog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
  jpa:
    generate-ddl: true
    show-sql: true
zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  routes:
    vlog-message-producer: /message-producer/**
    vlog-auth-server: /auth-server/**
  sensitive-headers:
  ratelimit:
    enabled: true
    repository: JPA
    default-policy-list:
      - limit: 1
        quota: 10
        refresh-interval: 3
        type:
          - url
          - httpmethod

auth:
  client:
    id: zuulProxy
    secret: 123456
  server:
    mapping-url: auth-server

